### PR TITLE
2.80_BETA

### PR DESCRIPTION
**Pull request by TurBoss**
this allows to use blender 2.80 beta

sorry for the reformat I can clean it if needed

### CODE REVIEW

**Comment by TurBoss** [comment]
forgot to mention that just runs 10x faster
:D

**Comment by olablt** [comment]
thats great! how is it working 10 times faster?

**Comment by TurBoss** [comment]
new blender beta 2.80 is faster indirectly speedups blendercam

i normally use parallel all 3.0 with 0.1mm steps in a 150x150mm surface and
2.79 tooks 40 or 50 minutes while now it only takes 5 min

**Comment by ksuprynowicz** [comment]
That's awesome!
I'll give it a try today :)

**Comment by olablt** [comment]
let me know if it is working for you too and how long it takes to install
it? any errors?..

I am using it with 2.79

**Comment by ksuprynowicz** [comment]
Great work!
I've just tried it and it's really fast indeed :)
I've downloaded most recent Blender 2.8 beta, and added Shapely using PIP package manager:

`  cd 2.80/python/bin/
./python3.7m -m ensurepip
./python3.7m -m pip install --upgrade pip setuptools wheel
./python3.7m -m pip install shapely
 `
And copied `scripts` directory from repository to `2.80`.
The only thing that didn't work for me was simulation - I've got "no computed path to simulate" message. I've not tried it with OpenCAMLib yet.

I think we should copy current master branch to "2.79" and then merge "2.80_BETA" with master. What are your opinions on this?

**Comment by TurBoss** [comment]
simulation and opencamlib is not tested sorry (I'm working on that)

for now we can keep 2.79 as master and merge this in 2.80 branch until blender is released

please dont merge to master until everything is fixed 
this PR is very experimental

Thanks for your interest guys

**Comment by ksuprynowicz** [comment]
Thanks!
I've merged this as "2.80_BETA" branch.

**Comment by TurBoss** [comment]
cool
I have setup a #blendercam room in freenode
and #blendercam:matrix.org room in the matrix

**Comment by TurBoss** [comment]
simulation fixed!

**Comment by TurBoss** [comment]
OpenCamLib is working
used https://github.com/aewallin/opencamlib <-- this one

**Comment by ksuprynowicz** [comment]
Thanks, simulation works perfectly now :)

I've noticed two more problems:
When using "Export chain gcode" on simple chain with one operation, I get:
`KeyError: 'bpy_prop_collection[key]: key "Operation_1" not found'`

When I create a Parallel strategy operation and click "calculate path" first time, it works well,
but on second time I get incorrect path with following message:
`progress{preparing collisions}
Operation_1
WARNING: no geometry data converted for Mesh Collision Shape (ob = cam_path_Operation_1)`

**Comment by TurBoss** [comment]
> Thanks, simulation works perfectly now :)
> 
> I've noticed two more problems:
> When using "Export chain gcode" on simple chain with one operation, I get:
> `KeyError: 'bpy_prop_collection[key]: key "Operation_1" not found'`


This should be fixed

 
> When I create a Parallel strategy operation and click "calculate path" first time, it works well,
> but on second time I get incorrect path with following message:
> `progress{preparing collisions} Operation_1 WARNING: no geometry data converted for Mesh Collision Shape (ob = cam_path_Operation_1)`

I'm with this, id doesn't happends with opencamlib

**Comment by TurBoss** [comment]
> > When I create a Parallel strategy operation and click "calculate path" first time, it works well,
> > but on second time I get incorrect path with following message:
> > `progress{preparing collisions} Operation_1 WARNING: no geometry data converted for Mesh Collision Shape (ob = cam_path_Operation_1)`
> 
> I'm with this, id doesn't happends with opencamlib

should be fixed now Thanks

**Comment by pppalain** [comment]
Please check curve functionality.  I had to convert curve to mesh to get a cutout.

**Comment by ksuprynowicz** [comment]
>  Please check curve functionality. I had to convert curve to mesh to get a cutout.

Can you post an example file that causes that problem?

**Comment by TurBoss** [comment]
yes please attach some example file

**Comment by pppalain** [comment]
just a simple circle with a simple cutout operation fails.  convert it to mesh and it works.
[curve_sample.zip](https://github.com/vilemduha/blendercam/files/2873304/curve_sample.zip)
image

**Comment by TurBoss** [comment]
thanks I'll take a look

**Comment by TurBoss** [comment]
I started the port of that but layers has been changed and is different now
it will took a bit

**Comment by TurBoss** [comment]
captura de pantalla de 2019-02-20 00-29-09

**Comment by pppalain** [comment]
thanks.  

Same thing but for text.

also verify cam tools with curve error comes up.
image

**Comment by pppalain** [comment]
only calculates path if object is selected before pressing button.  Otherwise this occures
image

**Comment by TurBoss** [comment]
ok i'll take a look

**Comment by pppalain** [comment]
curve cam tools no longer generate an error but intarsion should have a bit size argument - the other tools should have other arguments as well.

image

**Comment by pppalain** [comment]
autogenerate bridges not working
image

**Comment by pppalain** [comment]
auto generate bridges not working
image

**Comment by pppalain** [comment]
curve cam tools -> curve boolean: wants 2 selected curves even thought they are selected

**Comment by TurBoss** [comment]
captura de pantalla de 2019-02-23 04-06-28


I'm sure still much left but this looks fixed

**Comment by pppalain** [comment]
text alone still not fixed but curve tools appear to be working

**Comment by bostjannagode** [comment]
Dear, sorry, but im lost. I would like to try, butcan you tell me, is it supposed to work on windows 10? For now, i have issue in Preferences, when enabling BlenderCam, it says there is no Shapely module... How to start?

Best, Bostjan

**Comment by TurBoss** [comment]
> Dear, sorry, but im lost. I would like to try, but can you tell me, is it supposed to work on windows 10? For now, i have issue in Preferences, when enabling BlenderCam, it says there is no Shapely module... How to start?
> 
> Best, Bostjan

it requires a bit of manual work:
https://bootstrap.pypa.io/get-pip.py
place this script in your blender installation \ 2.80 \ Python \ bin \
open a CMD on windows navigate to your blender installation \ 2.80 \ Python \ bin \
and issue
```
python3.7m.exe getpip.py
```
then once finished:
```
python3.7m.exe -m pip install shapely
```
then launch blender and install the addon

can contain some typos as I write from memory

thanks for your interest

**Comment by TurBoss** [comment]
hello @ksuprynowicz can you please merge this to 2.80_BETA?
thanks

**Comment by ksuprynowicz** [comment]
Sure! I'm sorry for the late reply, I'll merge it today.

**Comment by ksuprynowicz** [comment]
I've merged it. Thank you for the contribution!

**Pull request merged**
