### PR TITLE
fix waterline by @palain

### PR DESCRIPTION
**Pull request by TurBoss**
this fixes waterline oprations

many thanks to @palain

### CODE REVIEW

**Comment by TurBoss** [comment]
Captura de pantalla de 2020-11-16 22-42-22

**Comment by TurBoss** [comment]
@ksuprynowicz can you please take a look?

Thnaks

**Comment by ksuprynowicz** [comment]
Thank you!

**Comment by ksuprynowicz** [comment]
I'm sorry for not merging earlier, I had a lot of work this month

**Pull request merged**
