### PR TITLE
Use opencamlib from blender python interpreter [WIP]

### PR DESCRIPTION
**Pull request by TurBoss**
this is very early working state :P
it will require to install opencamlib inside blender
described here

https://github.com/vilemduha/blendercam/wiki/Install-opencamlib-into-blender-2.80-on-linux#installing-opencamlib-in-blender

### CODE REVIEW

**Comment by TurBoss** [comment]
Captura de pantalla de 2020-03-25 04-04-38

**Comment by ksuprynowicz** [comment]
Thank you! I have lots of work at the moment, but I will merge it soon.

**Comment by TurBoss** [comment]
just found this project 
https://github.com/cwant/VTKBlender/
I'm trying to skip the need to write a stl to disk and pass the mesh fromblender to opencamlib directly

**Comment by TurBoss** [comment]
this last commit seems to work but requires trianglate :(

**Comment by ksuprynowicz** [comment]
Thanks!
I've just tested it, but I have a problem - the collisions don't seem to work:
ocl
When I deselect "use opencamlib" it all works fine. Any ideas?
I'll fix triangulate requirement after merging, but first it has to work.

**Comment by ksuprynowicz** [comment]
Another problem is Waterline operation stopped working, I get the following message:
`NameError: name 'operationSettingsToCSV' is not defined`
That's not much of a problem though, I'll fix it if I can get Parallel operation to work again.

**Comment by ksuprynowicz** [comment]
I nearly got it:
It seems that somehow transform isn't applied to mesh data even with bpy.ops.object.transform_apply, so the object is 1000 times smaller than it should be. I'll have to look why that happens.

**Comment by TurBoss** [comment]
Thank you so much

**Comment by TurBoss** [comment]
what I'm trying to do is remove the need to write to disk csv and stl files which takes lot of time

**Comment by ksuprynowicz** [comment]
> what I'm trying to do is remove the need to write to disk csv and stl files which takes lot of time
I agree. It was done due to opencamlib licensing, but now that they have changed license, there's no point anymore.
Thanks for your contribution. I've nearly fixed the problems, and it seems that VTKBlender won't be necessary too :)

**Comment by TurBoss** [comment]
amazing!
Thanks!

**Comment by ksuprynowicz** [comment]
I changed few things and the basic opencamlib operations should work now (at least they do for me). BlenderVTK is also no longer necessary, and without writing STL it's really fast.
I'll probably do waterlines and operations on groups tomorrow.

**Comment by TurBoss** [comment]
Hello @ksuprynowicz 
I'm getting thi error
```
➜  blender-2.82-linux64 ./blender
Read prefs: /home/turboss/.config/blender/2.82/config/userpref.blend
found bundled python: /home/turboss/Apps/blender-2.82-linux64/2.82/python
Read blend: /home/turboss/Documentos/untitled.blend
update chipload 
0.0001250000059371814
update offset
update chipload 
0.0001250000059371814
update offset
update chipload 
0.0001250000059371814
update offset
Info: Saved "untitled.blend"

CALCULATE
3
PARALLEL
progress{building path pattern}
progress{7.48984956741333}
SAMPLE Fin_Ball_3,0_Parallel
Info: Deleted 1 object(s)
bdc::setSTL()
ERROR: KDTree::build_node() called with tris->size()==0 ! 
blender: /home/turboss/Projetcs/opencamlib/src/common/kdtree.hpp:148: ocl::KDNode<BBObj>* ocl::KDTree<BBObj>::build_node(const std::__cxx11::list<ValueType>*, int, ocl::KDNode<BBObj>*) [with BBObj = ocl::Triangle]: Assertion `0' failed.
[1]    8342 abort (core dumped)  ./blender

**Comment by TurBoss** [comment]
[untitled.zip](https://github.com/vilemduha/blendercam/files/4618971/untitled.zip)
found the sample file here

**Comment by ksuprynowicz** [comment]
Can you try now? I accidentally deleted one line too much when cleaning up the code.
Also, it seems that there's some new bug in chunk resampling procedure that causes very high memory usage due to high number of cl-points. I ran out of memory on that sample, so I had to increase distance between paths. At least it works now:
test

**Comment by ksuprynowicz** [comment]
Right now oclResampleChunks seems to be completely broken.

**Comment by ksuprynowicz** [comment]
I've tested it a bit more, and oclResampleChunks works, but somehow samples way too many points. For example original operation may have only 245 cl-points but on resampling there are 1388 cl-points. Maybe you can help with it? I don't have any ideas how to fix it.

**Comment by ksuprynowicz** [comment]
After testing a bit more, the problem seems to be somewhere in connectChunksLow function. Here's how it worked in the previous version:

And in the new version:

Notice that some of the connecting parts of toolpath have way more points that specified by "distance along toolpath option"
This leads to heavily increased memory consumption, especially when there's a lot of connected paths.

**Comment by ksuprynowicz** [comment]
If I disable "stay low if possible" the problems get worse:

So it seems that the error is somewhere else.

**Comment by ksuprynowicz** [comment]
Works perfectly now, including waterlines :)

**Comment by TurBoss** [comment]
great will test in a bit

**Comment by TurBoss** [comment]
wow this is amazing thank you so much

**Comment by ksuprynowicz** [comment]
Thank you too! You did it, I just had to fix some bugs later :)

**Pull request merged**
